// Turns a Synthesis into the GitHub artifacts: inline comments + the top-level
// summary markdown. Pure and testable.

import { INLINE_MARKER } from './config';
import type { MergedFinding, Synthesis, Verdict } from './findings';
import type { InlineComment } from './github';
import type { Plan } from './policy';
import type { ReviewerResult } from './findings';

const VERDICT_LINE: Record<Verdict, string> = {
  MERGE: '✅ **Recommendation: MERGE** — nothing blocking survived the panel.',
  COMMENT: '💬 **Recommendation: COMMENT** — non-blocking issues worth a look.',
  BLOCK: '⛔ **Recommendation: BLOCK** — a confirmed blocking issue; resolve before merge.',
};

const SEV_LABEL: Record<string, string> = {
  blocker: '⛔ blocker',
  high: '🔴 high',
  medium: '🟡 medium',
  nit: '⚪ nit',
};

function agree(f: MergedFinding): string {
  return f.agreedBy.length > 1 ? ` _(agreed by ${f.agreedBy.join(', ')})_` : '';
}

/**
 * Per-reviewer panel status. Distinguishes three outcomes that must not read
 * alike: the seat errored and did NOT review (a model/server problem — e.g. an
 * empty-content or timeout failure), the seat reviewed and raised nothing, and
 * the seat reviewed and raised findings. An errored seat is not "no findings".
 */
function panelStatus(r: ReviewerResult): string {
  if (r.error) return `❌ error — did not review (${r.error.slice(0, 140)})`;
  if (r.findings.length === 0) return '✅ reviewed — no findings';
  const n = r.findings.length;
  return `✅ reviewed — ${n} finding${n === 1 ? '' : 's'}`;
}

export function buildInlineComments(synth: Synthesis): InlineComment[] {
  const out: InlineComment[] = [];
  for (const f of synth.findings) {
    if (!f.inline || f.line == null) continue;
    out.push({
      path: f.path,
      line: f.line,
      body: `${INLINE_MARKER}\n**${SEV_LABEL[f.severity] ?? f.severity}: ${f.title}**${agree(f)}\n\n${f.body}`,
    });
  }
  return out;
}

export function buildSummaryMarkdown(
  plan: Plan,
  reviewers: ReviewerResult[],
  synth: Synthesis,
): string {
  const inlineCount = synth.findings.filter((f) => f.inline).length;
  const offDiff = synth.findings.filter((f) => !f.inline && f.severity !== 'nit');
  const nits = synth.findings.filter((f) => f.severity === 'nit');

  const panel = reviewers.map((r) => `- **${r.title}** — \`${r.model}\` — ${panelStatus(r)}`).join('\n');

  const lines: string[] = [
    '## 🤖 Multi-model review',
    '',
    VERDICT_LINE[synth.verdict],
    '',
    synth.summary,
    '',
    `**Plan:** \`${plan.bucket}\` · ${reviewers.length} reviewer(s) · ${inlineCount} inline comment(s)`,
    '',
    '<details><summary>Panel</summary>',
    '',
    panel,
    '',
    '</details>',
  ];

  if (offDiff.length) {
    lines.push('', '### Findings not on changed lines');
    for (const f of offDiff) {
      const loc = f.line != null ? `\`${f.path}:${f.line}\`` : `\`${f.path}\``;
      lines.push(`- ${SEV_LABEL[f.severity] ?? f.severity} ${loc} — **${f.title}**${agree(f)}: ${f.body}`);
    }
  }

  if (nits.length) {
    lines.push('', '<details><summary>Nits</summary>', '');
    for (const f of nits) {
      const loc = f.line != null ? `\`${f.path}:${f.line}\`` : `\`${f.path}\``;
      lines.push(`- ${loc} — ${f.title}: ${f.body}`);
    }
    lines.push('', '</details>');
  }

  lines.push(
    '',
    '<sub>Generated by pr-review-ci — a diverse non-Claude panel via OpenRouter. Re-run with `/review`, `/review low`, or `/review high`.</sub>',
  );
  return lines.join('\n');
}
