// Turns a Synthesis into the GitHub artifacts: inline comments + the top-level
// summary markdown. Pure and testable.

import type { MergedFinding, Synthesis, Verdict } from './findings';
import type { InlineComment } from './github';
import type { Plan } from './policy';
import type { ReviewerResult } from './findings';

const VERDICT_LINE: Record<Verdict, string> = {
  MERGE: '✅ **Recommendation: MERGE** — nothing blocking survived the panel.',
  COMMENT: '💬 **Recommendation: COMMENT** — non-blocking issues worth a look.',
  BLOCK: '⛔ **Recommendation: BLOCK** — a confirmed blocking issue; resolve before merge.',
};

const SEV_LABEL: Record<string, string> = {
  blocker: '⛔ blocker',
  high: '🔴 high',
  medium: '🟡 medium',
  nit: '⚪ nit',
};

function agree(f: MergedFinding): string {
  return f.agreedBy.length > 1 ? ` _(agreed by ${f.agreedBy.join(', ')})_` : '';
}

export function buildInlineComments(synth: Synthesis): InlineComment[] {
  const out: InlineComment[] = [];
  for (const f of synth.findings) {
    if (!f.inline || f.line == null) continue;
    out.push({
      path: f.path,
      line: f.line,
      body: `**${SEV_LABEL[f.severity] ?? f.severity}: ${f.title}**${agree(f)}\n\n${f.body}`,
    });
  }
  return out;
}

export function buildSummaryMarkdown(
  plan: Plan,
  reviewers: ReviewerResult[],
  synth: Synthesis,
): string {
  const inlineCount = synth.findings.filter((f) => f.inline).length;
  const offDiff = synth.findings.filter((f) => !f.inline && f.severity !== 'nit');
  const nits = synth.findings.filter((f) => f.severity === 'nit');

  const panel = reviewers
    .map(
      (r) =>
        `- **${r.title}** — \`${r.model}\`${r.error ? ` — ⚠️ failed: ${r.error.slice(0, 120)}` : ''}`,
    )
    .join('\n');

  const lines: string[] = [
    '## 🤖 Multi-model review',
    '',
    VERDICT_LINE[synth.verdict],
    '',
    synth.summary,
    '',
    `**Plan:** \`${plan.bucket}\` · ${reviewers.length} reviewer(s) · ${inlineCount} inline comment(s)`,
    '',
    '<details><summary>Panel</summary>',
    '',
    panel,
    '',
    '</details>',
  ];

  if (offDiff.length) {
    lines.push('', '### Findings not on changed lines');
    for (const f of offDiff) {
      const loc = f.line != null ? `\`${f.path}:${f.line}\`` : `\`${f.path}\``;
      lines.push(`- ${SEV_LABEL[f.severity] ?? f.severity} ${loc} — **${f.title}**${agree(f)}: ${f.body}`);
    }
  }

  if (nits.length) {
    lines.push('', '<details><summary>Nits</summary>', '');
    for (const f of nits) {
      const loc = f.line != null ? `\`${f.path}:${f.line}\`` : `\`${f.path}\``;
      lines.push(`- ${loc} — ${f.title}: ${f.body}`);
    }
    lines.push('', '</details>');
  }

  lines.push(
    '',
    '<sub>Generated by pr-review-ci — a diverse non-Claude panel via OpenRouter. Re-run with `/review`, `/review low`, or `/review high`.</sub>',
  );
  return lines.join('\n');
}
